type User {
  id: Int!
  email: String!
  firstName: String
  lastName: String
}

type SignInPayload {
  accessToken: String!
  user: User!
}

type SignUpPayload {
  user: User!
}

input SignInInput {
  email: String!
  password: String!
}

input SignUpInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

# ------

type Mutation {
  signUp(input: SignUpInput!): SignUpPayload!
  signIn(input: SignInInput!): SignInPayload!
}
